[main]
include=~/.config/foot/themes/theme.ini
font=JetBrainsMono Nerd Font:size=12
shell=fish
term=xterm-256color
pad=8x8

[colors]
alpha=0.5
background=000000

[csd]
preferred=none

[selection]
# Approximate equivalent of Alacritty's selection background
background=555555
